from brownie import Wei

ONE_DAY = 24 * 60 * 60
ONE_WEEK = 7 * ONE_DAY
ONE_MONTH = 30 * ONE_DAY

MAX_UINT256 = 2 ** 256 - 1

DEFAULT_REWARDS_DURATION = ONE_MONTH
DEFAULT_TOTAL_REWARD = Wei(1000 * 10 ** 18)
DEFAULT_TOTAL_STAKED = Wei(100 * 10 ** 18)
DEFAULT_REWARD_PER_SECOND = DEFAULT_TOTAL_REWARD // DEFAULT_REWARDS_DURATION
